"""Demo flag on trainer availability.

Every other seeded entity carries ``is_demo``; this one did not, so slots
created for UI evaluation could not be told from a trainer's real published
hours.

The column is added with a server default because autogenerate emits a bare
NOT NULL, which fails outright on a table that already has rows. The default is
dropped afterwards so the model stays the only place the default lives.

Revision ID: 16ad09f49f39
Revises: a2d48c7ec518
Create Date: 2026-08-15 11:04:53.847089
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op

revision: str = "16ad09f49f39"
down_revision: str | None = "a2d48c7ec518"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trainer_availability",
        sa.Column("is_demo", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column("trainer_availability", "is_demo", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trainer_availability", "is_demo")
    # ### end Alembic commands ###
