"""initial gymflow schema

Revision ID: 263f304244af
Revises: 
Create Date: 2026-08-12 13:21:29.047675
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op

revision: str = '263f304244af'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('qr_secret', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('incentive_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('min_punctuality_pct', sa.Numeric(precision=5, scale=2, asdecimal=False), nullable=False),
    sa.Column('min_attendance_pct', sa.Numeric(precision=5, scale=2, asdecimal=False), nullable=False),
    sa.Column('max_late_count', sa.Integer(), nullable=False),
    sa.Column('max_early_exit_count', sa.Integer(), nullable=False),
    sa.Column('max_missing_checkout_count', sa.Integer(), nullable=False),
    sa.Column('review_band_pct', sa.Numeric(precision=5, scale=2, asdecimal=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incentive_rules_branch_id'), 'incentive_rules', ['branch_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=24), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('push_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_branch_id'), 'users', ['branch_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('attendance_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('person_type', sa.Enum('TRAINER', 'MEMBER', name='person_type'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('CHECK_IN', 'CHECK_OUT', name='event_type'), nullable=False),
    sa.Column('method', sa.Enum('QR', 'PIN', 'FINGERPRINT', 'RFID', 'FACE', 'MANUAL', name='capture_method'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_events_branch_id'), 'attendance_events', ['branch_id'], unique=False)
    op.create_index(op.f('ix_attendance_events_user_id'), 'attendance_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_attendance_events_work_date'), 'attendance_events', ['work_date'], unique=False)
    op.create_index('ix_events_branch_date', 'attendance_events', ['branch_id', 'work_date'], unique=False)
    op.create_index('ix_events_user_date', 'attendance_events', ['user_id', 'work_date'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_branch_id'), 'audit_logs', ['branch_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('event_key', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'SENT', 'FAILED', 'SUPPRESSED', name='notification_status'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_branch_id'), 'notifications', ['branch_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'key', name='uq_setting_scope_key')
    )
    op.create_index(op.f('ix_settings_branch_id'), 'settings', ['branch_id'], unique=False)
    op.create_table('trainers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=32), nullable=False),
    sa.Column('designation', sa.String(length=80), nullable=True),
    sa.Column('specialty', sa.String(length=120), nullable=True),
    sa.Column('joined_on', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_code'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_trainers_branch_id'), 'trainers', ['branch_id'], unique=False)
    op.create_table('incentive_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('punctuality_pct', sa.Numeric(precision=5, scale=2, asdecimal=False), nullable=False),
    sa.Column('attendance_pct', sa.Numeric(precision=5, scale=2, asdecimal=False), nullable=False),
    sa.Column('late_count', sa.Integer(), nullable=False),
    sa.Column('early_exit_count', sa.Integer(), nullable=False),
    sa.Column('absent_count', sa.Integer(), nullable=False),
    sa.Column('missing_checkout_count', sa.Integer(), nullable=False),
    sa.Column('completed_shifts', sa.Integer(), nullable=False),
    sa.Column('scheduled_shifts', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2, asdecimal=False), nullable=False),
    sa.Column('status', sa.Enum('ELIGIBLE', 'NOT_ELIGIBLE', 'NEEDS_REVIEW', name='incentive_status'), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['incentive_rules.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trainer_id', 'period_start', name='uq_incentive_period')
    )
    op.create_index(op.f('ix_incentive_results_branch_id'), 'incentive_results', ['branch_id'], unique=False)
    op.create_index(op.f('ix_incentive_results_trainer_id'), 'incentive_results', ['trainer_id'], unique=False)
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('member_code', sa.String(length=32), nullable=False),
    sa.Column('assigned_trainer_id', sa.Integer(), nullable=True),
    sa.Column('joined_on', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('external_ref', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_trainer_id'], ['trainers.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_code'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_members_branch_id'), 'members', ['branch_id'], unique=False)
    op.create_index(op.f('ix_members_external_ref'), 'members', ['external_ref'], unique=False)
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('grace_minutes', sa.Integer(), nullable=True),
    sa.Column('early_exit_grace_minutes', sa.Integer(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shifts_branch_id'), 'shifts', ['branch_id'], unique=False)
    op.create_index(op.f('ix_shifts_trainer_id'), 'shifts', ['trainer_id'], unique=False)
    op.create_index('ix_shifts_trainer_weekday', 'shifts', ['trainer_id', 'weekday'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'FROZEN', 'CANCELLED', name='membership_status'), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('pt_sessions_total', sa.Integer(), nullable=False),
    sa.Column('pt_sessions_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memberships_branch_id'), 'memberships', ['branch_id'], unique=False)
    op.create_index(op.f('ix_memberships_member_id'), 'memberships', ['member_id'], unique=False)
    op.create_table('trainer_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grace_minutes', sa.Integer(), nullable=False),
    sa.Column('early_exit_grace_minutes', sa.Integer(), nullable=False),
    sa.Column('check_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_in_method', sa.Enum('QR', 'PIN', 'FINGERPRINT', 'RFID', 'FACE', 'MANUAL', name='capture_method'), nullable=True),
    sa.Column('check_out_method', sa.Enum('QR', 'PIN', 'FINGERPRINT', 'RFID', 'FACE', 'MANUAL', name='capture_method'), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'ON_TIME', 'LATE', 'EARLY_EXIT', 'LATE_AND_EARLY_EXIT', 'ABSENT', 'MISSING_CHECKOUT', 'COMPLETED', name='attendance_status'), nullable=False),
    sa.Column('late_minutes', sa.Integer(), nullable=False),
    sa.Column('early_exit_minutes', sa.Integer(), nullable=False),
    sa.Column('worked_minutes', sa.Integer(), nullable=False),
    sa.Column('corrected_by_user_id', sa.Integer(), nullable=True),
    sa.Column('correction_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['corrected_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trainer_id', 'work_date', name='uq_trainer_attendance_day')
    )
    op.create_index('ix_trainer_attendance_branch_date', 'trainer_attendance', ['branch_id', 'work_date'], unique=False)
    op.create_index(op.f('ix_trainer_attendance_branch_id'), 'trainer_attendance', ['branch_id'], unique=False)
    op.create_index(op.f('ix_trainer_attendance_trainer_id'), 'trainer_attendance', ['trainer_id'], unique=False)
    op.create_index(op.f('ix_trainer_attendance_work_date'), 'trainer_attendance', ['work_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trainer_attendance_work_date'), table_name='trainer_attendance')
    op.drop_index(op.f('ix_trainer_attendance_trainer_id'), table_name='trainer_attendance')
    op.drop_index(op.f('ix_trainer_attendance_branch_id'), table_name='trainer_attendance')
    op.drop_index('ix_trainer_attendance_branch_date', table_name='trainer_attendance')
    op.drop_table('trainer_attendance')
    op.drop_index(op.f('ix_memberships_member_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_branch_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index('ix_shifts_trainer_weekday', table_name='shifts')
    op.drop_index(op.f('ix_shifts_trainer_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_branch_id'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_members_external_ref'), table_name='members')
    op.drop_index(op.f('ix_members_branch_id'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_incentive_results_trainer_id'), table_name='incentive_results')
    op.drop_index(op.f('ix_incentive_results_branch_id'), table_name='incentive_results')
    op.drop_table('incentive_results')
    op.drop_index(op.f('ix_trainers_branch_id'), table_name='trainers')
    op.drop_table('trainers')
    op.drop_index(op.f('ix_settings_branch_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_branch_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_branch_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_events_user_date', table_name='attendance_events')
    op.drop_index('ix_events_branch_date', table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_work_date'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_user_id'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_branch_id'), table_name='attendance_events')
    op.drop_table('attendance_events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_branch_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_incentive_rules_branch_id'), table_name='incentive_rules')
    op.drop_table('incentive_rules')
    op.drop_table('roles')
    op.drop_table('branches')
    # ### end Alembic commands ###
