"""Payments: what SLAM charged, and whether it arrived.

Additive. The three enum types are created with the table and dropped with it —
autogenerate does not emit the type drops, and leaving them behind makes a
re-upgrade fail with DuplicateObject.

Revision ID: a2d48c7ec518
Revises: ccc721cb9b7d
Create Date: 2026-08-15 07:06:00.423736
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op

revision: str = "a2d48c7ec518"
down_revision: str | None = "ccc721cb9b7d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("branch_id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("MEMBERSHIP", "PT", "GROUP_CLASS", "RENEWAL", "ADDON", name="payment_kind"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PAID", "REFUNDED", "CANCELLED", name="payment_status"),
            nullable=False,
        ),
        sa.Column(
            "method",
            sa.Enum("CASH", "CARD", "UPI", "BANK_TRANSFER", "OTHER", name="payment_method"),
            nullable=True,
        ),
        sa.Column("amount", sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
        sa.Column("discount", sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
        sa.Column("tax", sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("membership_id", sa.Integer(), nullable=True),
        sa.Column("pt_package_id", sa.Integer(), nullable=True),
        sa.Column("group_class_id", sa.Integer(), nullable=True),
        sa.Column("trainer_id", sa.Integer(), nullable=True),
        sa.Column("due_on", sa.Date(), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("collected_by_user_id", sa.Integer(), nullable=True),
        sa.Column("receipt_no", sa.String(length=32), nullable=True),
        sa.Column("notes", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["collected_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["group_class_id"], ["group_classes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["member_id"], ["members.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["membership_id"], ["memberships.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["pt_package_id"], ["pt_packages.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["trainer_id"],
            ["trainers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("receipt_no"),
    )
    op.create_index(op.f("ix_payments_branch_id"), "payments", ["branch_id"], unique=False)
    op.create_index(
        op.f("ix_payments_collected_by_user_id"), "payments", ["collected_by_user_id"], unique=False
    )
    op.create_index(op.f("ix_payments_due_on"), "payments", ["due_on"], unique=False)
    op.create_index(
        op.f("ix_payments_group_class_id"), "payments", ["group_class_id"], unique=False
    )
    op.create_index(op.f("ix_payments_kind"), "payments", ["kind"], unique=False)
    op.create_index(op.f("ix_payments_member_id"), "payments", ["member_id"], unique=False)
    op.create_index(op.f("ix_payments_membership_id"), "payments", ["membership_id"], unique=False)
    op.create_index(op.f("ix_payments_paid_at"), "payments", ["paid_at"], unique=False)
    op.create_index(op.f("ix_payments_pt_package_id"), "payments", ["pt_package_id"], unique=False)
    op.create_index(op.f("ix_payments_status"), "payments", ["status"], unique=False)
    op.create_index(op.f("ix_payments_trainer_id"), "payments", ["trainer_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payments_trainer_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_status"), table_name="payments")
    op.drop_index(op.f("ix_payments_pt_package_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_paid_at"), table_name="payments")
    op.drop_index(op.f("ix_payments_membership_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_member_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_kind"), table_name="payments")
    op.drop_index(op.f("ix_payments_group_class_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_due_on"), table_name="payments")
    op.drop_index(op.f("ix_payments_collected_by_user_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_branch_id"), table_name="payments")
    op.drop_table("payments")
    # Autogenerate does not drop the types it created. Without these a
    # downgrade followed by an upgrade fails with DuplicateObject.
    sa.Enum(name="payment_method").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="payment_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="payment_kind").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
