"""Trainer availability: the slots a trainer publishes as bookable.

Nothing consumes these yet — members still cannot book PT — so the table is
additive and the downgrade simply drops it.

Revision ID: ccc721cb9b7d
Revises: 20aa75faece9
Create Date: 2026-08-14 16:08:35.013609
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ccc721cb9b7d"
down_revision: str | None = "20aa75faece9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trainer_availability",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trainer_id", sa.Integer(), nullable=False),
        sa.Column("branch_id", sa.Integer(), nullable=False),
        sa.Column("slot_date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("booked_session_id", sa.Integer(), nullable=True),
        sa.Column("note", sa.String(length=160), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["booked_session_id"], ["pt_sessions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
        ),
        sa.ForeignKeyConstraint(["trainer_id"], ["trainers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "trainer_id", "slot_date", "start_time", name="uq_trainer_availability_slot"
        ),
    )
    op.create_index(
        op.f("ix_trainer_availability_booked_session_id"),
        "trainer_availability",
        ["booked_session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_trainer_availability_branch_id"),
        "trainer_availability",
        ["branch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_trainer_availability_slot_date"),
        "trainer_availability",
        ["slot_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_trainer_availability_trainer_id"),
        "trainer_availability",
        ["trainer_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trainer_availability_trainer_id"), table_name="trainer_availability")
    op.drop_index(op.f("ix_trainer_availability_slot_date"), table_name="trainer_availability")
    op.drop_index(op.f("ix_trainer_availability_branch_id"), table_name="trainer_availability")
    op.drop_index(
        op.f("ix_trainer_availability_booked_session_id"), table_name="trainer_availability"
    )
    op.drop_table("trainer_availability")
    # ### end Alembic commands ###
